language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

env:
  global: SCIDB_VER=19.11 ARROW_VER=0.16.0
  matrix:
    - SCIDB_IMG=-xenial
    - SCIDB_IMG=-centos-7

services:
  - docker

before_install:
  # - mkdir shim
  # - wget --no-verbose --output-document -
  #   https://github.com/Paradigm4/shim/archive/master.tar.gz
  #   | tar --extract --gzip --directory=.

  - docker pull rvernica/scidb:${SCIDB_VER}${SCIDB_IMG}

  - docker run
    --detach
    --env ARROW_VER=${ARROW_VER}
    --name scidb
    --publish 8080:8080
    --volume /sys/fs/cgroup:/sys/fs/cgroup:ro
    --volume /tmp/$(mktemp --directory):/run
    --volume /tmp:/tmp
    --volume `pwd`:/accelerated_io_tools
    rvernica/scidb:${SCIDB_VER}${SCIDB_IMG}

  - if [ "$SCIDB_IMG" = "-centos-7" ]; then
      docker exec scidb /opt/scidb/$SCIDB_VER/bin/scidbctl.py start scidb ;
      docker exec scidb systemctl start shimsvc ;
    fi

  - while ! curl http://localhost:8080/version; do sleep 5; done

install:
  - docker exec scidb /accelerated_io_tools/tests/docker-install.sh

  # - docker exec scidb make --directory=/accelerated_io_tools/shim-master service

  - pip install --upgrade scidb-py

script:
  - docker exec scidb /accelerated_io_tools/tests/test.sh
  - docker exec scidb /accelerated_io_tools/tests/test-skip.sh
  - docker exec scidb /accelerated_io_tools/tests/test_arrow.sh
  - ./tests/test_arrow.sh "docker exec scidb"

after_failure:
  - cat tests/test.out
  - cat tests/test-skip.out
  - cat tests/test_arrow.out
  - docker logs scidb
