name: Test Suite

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/rvernica/scidb:19.11-xenial
      volumes:
        - /dev/shm
      ports:
        - 8080:8080
        - 8083:8083
      env:
        ARROW_VER: 3.0.0

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      # - name: Wait for SciDB to start
      #   run: while ! curl http://localhost:8080/version; do sleep 5; done

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set-up Docker container
        run: tests/docker-install.sh

      - name: Run tests
        run: |
          tests/test.sh
          tests/test-skip.sh
          tests/test_arrow.sh
