name: Test Suite

on: [push]

env:
  SCIDB_VER: 19.11

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image: [xenial, centos-7]

    services:
      scidb:
        image: ghcr.io/rvernica/scidb:${{ env.SCIDB_VER }}-${{ matrix.image }}
        volumes:
          - /dev/shm
          - /home/runner/work:/__w
        ports:
          - 8080:8080
          - 8083:8083
        env:
          ARROW_VER: 3.0.0
        options: --name scidb

    steps:
      - name: Start SciDB in CentOS-7
        run: >-
          docker exec scidb
          /opt/scidb/${{ env.SCIDB_VER }}/bin/scidbctl.py start scidb
        if: ${{ matrix.image == 'centos-7' }}

      - name: Start Shim in CentOS-7
        run: docker exec scidb systemctl start shimsvc
        if: ${{ matrix.image == 'centos-7' }}

      - name: Wait for SciDB to start
        run: while ! curl http://localhost:8080/version; do sleep 5; done

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set-up Docker container
        run: >-
          docker exec scidb
          /__w/accelerated_io_tools/accelerated_io_tools/tests/docker-install.sh

      # - name: Run tests 1/3
      #   run: tests/test.sh

      # - name: Run tests 2/3
      #   run: tests/test-skip.sh

      # - name: Run tests 3/3
      #   run: tests/test_arrow.sh
