name: Test Suite

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/rvernica/scidb:19.11-xenial
      volumes:
        - /dev/shm
      ports:
        - 8080:8080
        - 8083:8083
      env:
        ARROW_VER: 3.0.0
      options: --init

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Start-up Services and SciDB in Docker container
        run: /docker-entrypoint.sh echo

      - name: Set-up Docker container
        run: tests/docker-install.sh

      - name: Run tests
        run: |
          tests/test.sh
          tests/test-skip.sh
          tests/test_arrow.sh
